In [1]:
import numpy as np

x = [[1142432, 2434243, 143433],
    [431431714, 4342524, 644314212],
    [124341743, 4343102, 2924321432],
    [1042431, 43143111, 4121423],
    [324134, 4321123, 315143214], 
    [434341, 4311431, 4314321],
    [43434211, 43424311, 4314314341],
    [4314341, 4314341431, 4341231431],
    [43143143431, 431321412431, 4314343431],
    [143144214331, 143143143143, 14314343241]]

x = np.array(x)

# Matriz de covariancia (necesitamos x.T, porque se calcula la covarianza entre las filas)
S = np.cov(x.T)
print("\nS:")
print(S)

# lambdas y us de S
lambdas, us  = np.linalg.eig(S)

# Sort
idx = np.argsort(lambdas)[::-1] # indices de lambdas ordenados de mayor a menor
lambdas = lambdas[idx]      # lambdas ordenados
us = us[:, idx]       # us ordenados
print("\nSorted eigenvalues:")
print(lambdas)
print("\nSorted eigenvectors:")
print(us)

# Print de datos
print("\nDatos originales:")
print(x)

# Proyectar los datos de R^3 a R^2 (lo vamos a usar para S')
x_pca = x @ us[:, :2] # @ es el producto entre matrices (x con los dos primeros eigenvectores)
print("\nProyección en R^2:")
print(x_pca)

# Projectar de R a R^1
x_pca2 = x @ us[:, :1] 
print("\nProyectados R^1:")
print(x_pca2)


S:
[[2.09543003e+21 3.14218780e+21 1.83702928e+20]
 [3.14218780e+21 1.92262142e+22 2.36004001e+20]
 [1.83702928e+20 2.36004001e+20 1.92046387e+19]]

Sorted eigenvalues:
[1.97879178e+22 1.54996377e+21 2.96734219e+18]

Sorted eigenvectors:
[[ 0.17498278  0.98030748 -0.09153287]
 [ 0.98448059 -0.17547217  0.00273633]
 [ 0.01337903  0.09059114  0.9957983 ]]

Datos originales:
[[     1142432      2434243       143433]
 [   431431714      4342524    644314212]
 [   124341743      4343102   2924321432]
 [     1042431     43143111      4121423]
 [      324134      4321123    315143214]
 [      434341      4311431      4314321]
 [    43434211     43424311   4314314341]
 [     4314341   4314341431   4341231431]
 [ 43143143431 431321412431   4314343431]
 [143144214331 143143143143  14314343241]]

Proyección en R^2:
[[ 2.59828990e+06  7.05786489e+05]
 [ 8.83885495e+07  4.80542907e+08]
 [ 6.51579474e+07  3.86048671e+08]
 [ 4.27111034e+07 -6.17514810e+06]
 [ 8.52709010e+06  2.81086983e+07]
 [ 4.378

In [2]:
print("Datos en R^2:")
print(x_pca)

# S'
S_pca = np.cov(x_pca.T)
print("\nS':")
print(S_pca)

# lambdas' y us' de S'
lambdas_pca, us_pca = np.linalg.eig(S_pca)

# Sort
idx_pca = np.argsort(lambdas_pca)[::-1]     # indices de lambdas ordenados de mayor a menor
lambdas_pca = lambdas_pca[idx_pca]      # lambdas ordenados
us_pca = us_pca[:, idx_pca] # us ordenados
print("\nSorted lambdas de S':")
print(lambdas_pca)
print("\nSorted eigenvectores de S':")
print(us_pca)

# Proyectar los datos de R^2 a R^1 usando S'
x_pca_1 = x_pca @ us_pca[:, :1]   
print("\nDatos proyectados:")
print(x_pca_1)
print(":o")

Datos en R^2:
[[ 2.59828990e+06  7.05786489e+05]
 [ 8.83885495e+07  4.80542907e+08]
 [ 6.51579474e+07  3.86048671e+08]
 [ 4.27111034e+07 -6.17514810e+06]
 [ 8.52709010e+06  2.81086983e+07]
 [ 4.37824375e+06  6.00908402e+04]
 [ 1.08071971e+08  4.25797795e+08]
 [ 4.30622179e+09 -3.59540364e+08]
 [ 4.32234587e+11 -3.30005178e+10]
 [ 1.66160930e+11  1.16504459e+11]]

S':
[[1.97879178e+22 3.72827022e+06]
 [3.72827022e+06 1.54996377e+21]]

Sorted lambdas de S':
[1.97879178e+22 1.54996377e+21]

Sorted eigenvectores de S':
[[ 1.0000000e+00 -2.0442371e-16]
 [ 0.0000000e+00  1.0000000e+00]]

Datos proyectados:
[[2.59828990e+06]
 [8.83885495e+07]
 [6.51579474e+07]
 [4.27111034e+07]
 [8.52709010e+06]
 [4.37824375e+06]
 [1.08071971e+08]
 [4.30622179e+09]
 [4.32234587e+11]
 [1.66160930e+11]]
:o


In [3]:
diferencia = x_pca_1 - x_pca2
print("\nDiferencia de proyecciones:")
print(diferencia)


Diferencia de proyecciones:
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 7.45058060e-09]
 [ 7.45058060e-09]
 [ 0.00000000e+00]
 [-9.31322575e-10]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


In [4]:
print("diferencia de eigenvalores:")
print(lambdas_pca - lambdas[:1])

diferencia de eigenvalores:
[ 0.0000000e+00 -1.8237954e+22]
